ALTER TYPE accounting_core_transaction_violation_code_type ADD VALUE 'NET_OFF_TX';
ALTER TYPE accounting_core_transaction_violation_code_type ADD VALUE 'TX_INTERNAL_NUMBER_MUST_BE_PRESENT';
ALTER TYPE accounting_core_transaction_violation_code_type ADD VALUE 'DOCUMENT_NAME_MUST_BE_SET';
ALTER TYPE accounting_core_transaction_violation_code_type ADD VALUE 'FX_RATE_MUST_BE_GREATER_THAN_ZERO';
ALTER TYPE accounting_core_transaction_violation_code_type ADD VALUE 'ENTRY_DATE_MUST_BE_PRESENT';