-- Funding module – Spending/Funding feature schema (consolidated).
--
-- The funding event is the root entity spanning projects, milestones, their per-event
-- allocations and (for SPENDING events) line items.
--
-- All primary keys are deterministic SHA3-256 hashes (64 hex chars) derived from natural
-- business keys, generated by the *Entity.id(...) factory methods:
--   * funding_project.project_id     = hash(organisation_id :: external_project_id)        [root]
--                                      hash(parent_project_id :: external_project_id)       [sub]
--   * funding_milestone.milestone_id = hash(project_id :: external_milestone_id)            [keyed]
--                                      hash(project_id :: title :: amount :: ccy :: date)   [anonymous]
--   * funding_event.event_id         = hash(organisation_id :: type :: funding_id :: funding_hash :: ccy)
--   * funding_spending_item.item_id  = hash(event_id :: line_no)
-- _aud tables back Hibernate Envers auditing and reference the shared revinfo table.

-- ============================================================
-- funding_project (self-referential: root + sub-projects)
-- ============================================================

CREATE TABLE IF NOT EXISTS funding_project (
    project_id          CHAR(64)        NOT NULL,
    organisation_id     VARCHAR(255)    NOT NULL,
    funding_id          VARCHAR(255),
    external_project_id VARCHAR(255)    NOT NULL,
    project_title       VARCHAR(255)    NOT NULL,
    total_amount        NUMERIC(30, 10),
    currency            VARCHAR(10),
    parent_project_id   CHAR(64),

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_funding_project PRIMARY KEY (project_id),
    CONSTRAINT fk_funding_project_parent FOREIGN KEY (parent_project_id)
        REFERENCES funding_project (project_id) ON DELETE CASCADE,
    -- One project per funding grant within an organisation (NULL for sub-projects).
    CONSTRAINT uq_funding_project_org_funding_id UNIQUE (organisation_id, funding_id)
);

-- external_project_id is unique per organisation for root projects, and per parent for
-- sub-projects (two sub-projects "WP-1" under different parents are distinct entities).
CREATE UNIQUE INDEX IF NOT EXISTS uq_funding_project_org_external_id_root
    ON funding_project (organisation_id, external_project_id)
    WHERE parent_project_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_funding_project_parent_external_id_sub
    ON funding_project (parent_project_id, external_project_id)
    WHERE parent_project_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS funding_project_aud (
    project_id          CHAR(64)        NOT NULL,
    organisation_id     VARCHAR(255),
    funding_id          VARCHAR(255),
    external_project_id VARCHAR(255),
    project_title       VARCHAR(255),
    total_amount        NUMERIC(30, 10),
    currency            VARCHAR(10),
    parent_project_id   CHAR(64),

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    rev     INTEGER  NOT NULL,
    revtype SMALLINT,

    CONSTRAINT pk_funding_project_aud PRIMARY KEY (project_id, rev, revtype),
    CONSTRAINT fk_funding_project_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

-- ============================================================
-- funding_milestone
-- ============================================================

CREATE TABLE IF NOT EXISTS funding_milestone (
    milestone_id          CHAR(64)        NOT NULL,
    project_id            CHAR(64)        NOT NULL,
    external_milestone_id VARCHAR(255),
    milestone_title       VARCHAR(255)    NOT NULL,
    milestone_amount      NUMERIC(30, 10) NOT NULL,
    currency              VARCHAR(10)     NOT NULL,
    milestone_date        DATE            NOT NULL,

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_funding_milestone PRIMARY KEY (milestone_id),
    CONSTRAINT fk_funding_milestone_project FOREIGN KEY (project_id)
        REFERENCES funding_project (project_id) ON DELETE CASCADE,
    -- User-defined milestone id is unique within its project (NULL for anonymous milestones).
    CONSTRAINT uq_funding_milestone_project_external_id UNIQUE (project_id, external_milestone_id)
);

CREATE TABLE IF NOT EXISTS funding_milestone_aud (
    milestone_id          CHAR(64)        NOT NULL,
    project_id            CHAR(64),
    external_milestone_id VARCHAR(255),
    milestone_title       VARCHAR(255),
    milestone_amount      NUMERIC(30, 10),
    currency              VARCHAR(10),
    milestone_date        DATE,

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    rev     INTEGER  NOT NULL,
    revtype SMALLINT,

    CONSTRAINT pk_funding_milestone_aud PRIMARY KEY (milestone_id, rev, revtype),
    CONSTRAINT fk_funding_milestone_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

-- ============================================================
-- funding_event
-- ============================================================

CREATE TABLE IF NOT EXISTS funding_event (
    event_id        CHAR(64)        NOT NULL,
    organisation_id VARCHAR(255)    NOT NULL,
    event_type      VARCHAR(20)     NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'DRAFT',
    funding_id      VARCHAR(255)    NOT NULL,
    funding_hash    VARCHAR(255),
    funding_entity  VARCHAR(255),
    tx_hash         VARCHAR(255),
    total_amount    NUMERIC(30, 10) NOT NULL DEFAULT 0,
    currency        VARCHAR(10)     NOT NULL,
    ledger_dispatch_approved BOOLEAN,
    ledger_dispatch_status   VARCHAR(20),
    ledger_dispatch_status_error_reason TEXT,

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_funding_event PRIMARY KEY (event_id),
    CONSTRAINT chk_funding_event_type   CHECK (event_type IN ('FUNDING', 'SPENDING', 'REFUND')),
    CONSTRAINT chk_funding_event_status CHECK (status     IN ('DRAFT', 'PUBLISHED'))
);

CREATE TABLE IF NOT EXISTS funding_event_aud (
    event_id        CHAR(64)     NOT NULL,
    organisation_id VARCHAR(255),
    event_type      VARCHAR(20),
    status          VARCHAR(20),
    funding_id      VARCHAR(255),
    funding_hash    VARCHAR(255),
    funding_entity  VARCHAR(255),
    tx_hash         VARCHAR(255),
    total_amount    NUMERIC(30, 10),
    currency        VARCHAR(10),
    ledger_dispatch_approved BOOLEAN,
    ledger_dispatch_status   VARCHAR(20),
    ledger_dispatch_status_error_reason TEXT,

    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,

    rev     INTEGER  NOT NULL,
    revtype SMALLINT,

    CONSTRAINT pk_funding_event_aud PRIMARY KEY (event_id, rev, revtype),
    CONSTRAINT fk_funding_event_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

-- ============================================================
-- funding_spending_item
-- ============================================================

CREATE TABLE IF NOT EXISTS funding_spending_item (
    item_id      CHAR(64)     NOT NULL,
    event_id     CHAR(64)     NOT NULL,
    category     VARCHAR(255),
    vendor       VARCHAR(255),
    amount_fcy   NUMERIC(30, 10),
    currency     VARCHAR(10)  NOT NULL,
    fx_rate      NUMERIC(30, 15),
    amount_rcy   NUMERIC(30, 10),
    spend_date   DATE         NOT NULL,
    hash         VARCHAR(255),
    notes        TEXT,

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_funding_spending_item PRIMARY KEY (item_id),
    CONSTRAINT fk_funding_item_event FOREIGN KEY (event_id)
        REFERENCES funding_event (event_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS funding_spending_item_aud (
    item_id      CHAR(64)     NOT NULL,
    event_id     CHAR(64),
    category     VARCHAR(255),
    vendor       VARCHAR(255),
    amount_fcy   NUMERIC(30, 10),
    currency     VARCHAR(10),
    fx_rate      NUMERIC(30, 15),
    amount_rcy   NUMERIC(30, 10),
    spend_date   DATE,
    hash         VARCHAR(255),
    notes        TEXT,

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    rev     INTEGER  NOT NULL,
    revtype SMALLINT,

    CONSTRAINT pk_funding_spending_item_aud PRIMARY KEY (item_id, rev, revtype),
    CONSTRAINT fk_funding_spending_item_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

-- ============================================================
-- funding_event_milestone_allocation (event <-> milestone; project implicit via milestone)
-- ============================================================

CREATE TABLE IF NOT EXISTS funding_event_milestone_allocation (
    event_id         CHAR(64) NOT NULL,
    milestone_id     CHAR(64) NOT NULL,
    allocated_amount NUMERIC(30, 10),

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_funding_ema PRIMARY KEY (event_id, milestone_id),
    CONSTRAINT fk_fema_event     FOREIGN KEY (event_id)     REFERENCES funding_event     (event_id)     ON DELETE CASCADE,
    CONSTRAINT fk_fema_milestone FOREIGN KEY (milestone_id) REFERENCES funding_milestone (milestone_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS funding_event_milestone_allocation_aud (
    event_id         CHAR(64) NOT NULL,
    milestone_id     CHAR(64) NOT NULL,
    allocated_amount NUMERIC(30, 10),

    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,

    rev     INTEGER  NOT NULL,
    revtype SMALLINT,

    CONSTRAINT pk_funding_ema_aud PRIMARY KEY (event_id, milestone_id, rev, revtype),
    CONSTRAINT fk_funding_ema_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
