-- LOB-2365 follow-up: deleting a milestone/sub-project/project must no longer silently take its
-- funding_event_milestone_allocation rows with it. fk_fema_milestone (see V1.6_100_9) is
-- ON DELETE CASCADE, so today deleting a milestone row cascades straight through to any allocation row
-- referencing it. Instead, an allocation row must survive its milestone being deleted, standing as a
-- deliberately dangling reference that an event's own ERROR status already flags for a human to review.
-- EventMilestoneAllocationEntity's own milestone association is a plain lazy @ManyToOne with no
-- @NotFound(IGNORE) or similar — code must resolve a dangling milestone_id via MilestoneRepository
-- #findById (which correctly returns empty) rather than the entity's own getMilestone(), which would
-- throw EntityNotFoundException on a dangling row; only JPQL path navigation (a safe SQL join that
-- simply excludes dangling rows) is used against this association today. Dropping the FK gives up the
-- database's own guarantee that milestone_id always resolves to a live row — a deliberate trade for
-- keeping the allocation itself, and the money it recorded, intact.
ALTER TABLE funding_event_milestone_allocation DROP CONSTRAINT fk_fema_milestone;
