export enum TransactionPendingStatus {
    VAT_DATA_NOT_FOUND = "VAT_DATA_NOT_FOUND",
    COST_CENTER_DATA_NOT_FOUND = "COST_CENTER_DATA_NOT_FOUND",
    CHART_OF_ACCOUNT_NOT_FOUND = "CHART_OF_ACCOUNT_NOT_FOUND"
}