package org.cardanofoundation.lob.app.funding.util;

public final class ErrorTitleConstants {

    private ErrorTitleConstants() {}

    public static final String PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND";
    public static final String PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS";
    public static final String PROJECT_FIELDS_REQUIRED = "PROJECT_FIELDS_REQUIRED";
    public static final String PROJECT_AMOUNT_INVALID = "PROJECT_AMOUNT_INVALID";
    public static final String PARENT_PROJECT_NOT_FOUND = "PARENT_PROJECT_NOT_FOUND";
    public static final String PARENT_PROJECT_ORG_MISMATCH = "PARENT_PROJECT_ORG_MISMATCH";
    public static final String PROJECT_CIRCULAR_DEPENDENCY = "PROJECT_CIRCULAR_DEPENDENCY";
    public static final String SUBPROJECT_AMOUNT_EXCEEDS_PARENT = "SUBPROJECT_AMOUNT_EXCEEDS_PARENT";
    public static final String SUBPROJECT_TOTAL_EXCEEDS_PARENT = "SUBPROJECT_TOTAL_EXCEEDS_PARENT";
    public static final String MILESTONE_NOT_FOUND = "MILESTONE_NOT_FOUND";
    public static final String MILESTONE_FIELDS_REQUIRED = "MILESTONE_FIELDS_REQUIRED";
    public static final String MILESTONE_DATE_IN_PAST = "MILESTONE_DATE_IN_PAST";
    public static final String MILESTONE_AMOUNT_INVALID = "MILESTONE_AMOUNT_INVALID";
    public static final String MILESTONE_AMOUNT_EXCEEDS_PROJECT = "MILESTONE_AMOUNT_EXCEEDS_PROJECT";
    public static final String MILESTONE_TOTAL_EXCEEDS_PROJECT = "MILESTONE_TOTAL_EXCEEDS_PROJECT";
    public static final String MILESTONE_NOT_ALLOWED_WITH_SUBPROJECTS = "MILESTONE_NOT_ALLOWED_WITH_SUBPROJECTS";
    public static final String SUBPROJECT_NOT_ALLOWED_WITH_MILESTONES = "SUBPROJECT_NOT_ALLOWED_WITH_MILESTONES";
    public static final String ALLOCATION_AMOUNT_INVALID = "ALLOCATION_AMOUNT_INVALID";
    public static final String ALLOCATION_AMOUNT_REQUIRED = "ALLOCATION_AMOUNT_REQUIRED";
    public static final String ALLOCATION_EXCEEDS_MILESTONE = "ALLOCATION_EXCEEDS_MILESTONE";
    public static final String ALLOCATION_TOTAL_EXCEEDS_PROJECT = "ALLOCATION_TOTAL_EXCEEDS_PROJECT";
    public static final String EVENT_AMOUNT_INVALID = "EVENT_AMOUNT_INVALID";
    public static final String SPENDING_EVENT_NOT_FOUND = "SPENDING_EVENT_NOT_FOUND";
    public static final String SPENDING_EVENT_ALREADY_EXISTS = "SPENDING_EVENT_ALREADY_EXISTS";
    public static final String SPENDING_EVENT_ALREADY_PUBLISHED = "SPENDING_EVENT_ALREADY_PUBLISHED";

}
