package org.cardanofoundation.lob.app.accounting_reporting_core.domain.core;

public enum TransactionViolationCode {

    DOCUMENT_MUST_BE_PRESENT, //ERP
    DOCUMENT_NAME_MUST_BE_SET, //ERP
    TX_CANNOT_BE_ALTERED,
    ACCOUNT_CODE_CREDIT_IS_EMPTY,//ERP
    ACCOUNT_CODE_DEBIT_IS_EMPTY, //ERP
    LCY_BALANCE_MUST_BE_ZERO, //ERP
    FCY_BALANCE_MUST_BE_ZERO, //ERP
    AMOUNT_LCY_IS_ZERO, //ERP
    AMOUNT_FCY_IS_ZERO, //EPR
    TRANSACTION_TYPE_UNKNOWN, //ERP
    NET_OFF_TX, //ERP
    TX_INTERNAL_NUMBER_MUST_BE_PRESENT, //ERP
    FX_RATE_MUST_BE_GREATER_THAN_ZERO, //ERP
    ENTRY_DATE_MUST_BE_PRESENT, // ERP
    ALL_TX_ITEMS_ERASED, //ERP
    TX_VERSION_CONFLICT_TX_NOT_MODIFIABLE, //ERP
    TX_VALIDATION_ERROR, //LOB && ERP
    VAT_DATA_NOT_FOUND, //LOB
    CORE_CURRENCY_NOT_FOUND, //LOB
    CURRENCY_DATA_NOT_FOUND, //LOB
    COST_CENTER_DATA_NOT_FOUND, //LOB
    PROJECT_DATA_NOT_FOUND, //LOB
    CHART_OF_ACCOUNT_NOT_FOUND, //LOB
    EVENT_DATA_NOT_FOUND, //LOB
    ORGANISATION_DATA_NOT_FOUND, //LOB
    JOURNAL_DUMMY_ACCOUNT_MISSING //LOB

}
