ALTER TABLE organisation_cost_center DROP COLUMN external_customer_code;
ALTER TABLE organisation_cost_center_aud DROP COLUMN external_customer_code;
ALTER TABLE organisation_project DROP COLUMN external_customer_code;
ALTER TABLE organisation_project_aud DROP COLUMN external_customer_code;