name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test
        run: |
         ./gradlew clean test jacocoTestReport
      - name: Spotless
        run : |
          ./gradlew spotlessCheck
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          ./gradlew sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=cardano-foundation \
          -Dsonar.projectKey=cardano-foundation_cf-lob-platform \
          -Dsonar.pullrequest.key=${{github.event.pull_request.number}} \
          -Dsonar.pullrequest.branch=${{github.head_ref}} \
          -Dsonar.pullrequest.base=${{ github.base_ref }} \
  mutation-test-organisation:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :organisation:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/

  mutation-test-blockchain_publisher:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :blockchain_publisher:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/

  mutation-test-blockchain_common:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :blockchain_common:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/

  mutation-test-accounting_reporting_core:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :accounting_reporting_core:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/

  mutation-test-blockchain_reader:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :blockchain_reader:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/

  mutation-test-netsuite_altavia_erp_adapter:
    needs: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: PiTest
        run: |
          ./gradlew clean :netsuite_altavia_erp_adapter:pitest
      - name: Publish mutation test report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          folder: build/reports/pitest/
          target-folder: mutation-report/