name: Build

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

env:
  PRIVATE_DOCKER_REGISTRY_URL: ${{ secrets.GITLAB_DOCKER_REGISTRY_URL }}
  PRIVATE_DOCKER_REGISTRY_USER: Deploy-Token
  PRIVATE_DOCKER_REGISTRY_PASS: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}
  GITLAB_MAVEN_REGISTRY_URL: ${{ secrets.GITLAB_MAVEN_REGISTRY_URL }}
  GITLAB_MAVEN_REGISTRY_PASS: ${{ secrets.GITLAB_MAVEN_REGISTRY_PASS }}
  MAVEN_CENTRAL_OSSRH_USERNAME: ${{ secrets.MAVEN_CENTRAL_OSSRH_USERNAME }}
  MAVEN_CENTRAL_OSSRH_TOKEN: ${{ secrets.MAVEN_CENTRAL_OSSRH_TOKEN }}
  DOCKER_PUSH: true

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: ⛮ cf-gha-baseline
        uses: cardano-foundation/cf-gha-workflows/./actions/cf-gha-baseline@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_DOCKER_REGISTRY_URL: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          PRIVATE_DOCKER_REGISTRY_USER: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          PRIVATE_DOCKER_REGISTRY_PASS: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}
          HUB_DOCKER_COM_USER: ${{ secrets.HUB_DOCKER_COM_USER }}
          HUB_DOCKER_COM_PASS: ${{ secrets.HUB_DOCKER_COM_PASS }}
          DOCKER_REGISTRIES: "${{ secrets.DOCKER_REGISTRIES }}"

      - name: GPG checks
        run: |
          which gpg
          gpg --version

      - name: Decode GPG Key
        run: |
          mkdir -p ~/.gradle/
          echo "${{ secrets.MAVEN_CENTRAL_GPG_KEY_BASE64 }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
          echo "${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --import ~/.gradle/secring.gpg
          gpg --keyserver hkps://keys.openpgp.org --send-key BEFB6B63A980310BB92A65365E362818AF79A015

      - name: Gradle publish
        run: |
          case "${TRIGGERING_REF}" in 
            pr|branch)
              VERSION_PUBLISH=${DOCKER_VERSIONED_COMMIT_GHRUNID_TAG}
              ;;
            tag)
              VERSION_PUBLISH=${TAG_NAME}
              ;;
          esac
          ./gradlew clean build -Pversion=${VERSION_PUBLISH} \
            -Psign \
            -Psigning.gnupg.keyId="BEFB6B63A980310BB92A65365E362818AF79A015" \
            -Psigning.gnupg.passphrase="${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}" \
            -Psigning.secretKeyRingFile="${HOME}/.gradle/secring.gpg" \
            publish

      - name:  🌍 earthly (docker build and push)
        run: |
          earthly +docker-publish \
            --PUSH=${DOCKER_PUSH} \
            --DOCKER_REGISTRIES="${{ env.DOCKER_REGISTRIES_FILTERED }}" \
            --DOCKER_IMAGES_EXTRA_TAGS="${EARTHLY_DOCKER_IMAGES_EXTRA_TAGS}"

      - name: Generate SBOM
        run: ./gradlew cyclonedxBom

      - name: Upload SBOM to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: build/reports/bom.xml
