name: Sonar Main Branch

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test
        run: |
          ./gradlew clean test jacocoTestReport
      - name: Spotless
        run : |
          ./gradlew spotlessCheck
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_PR_KEY: ${{ github.event.pull_request.number }}
          SONAR_PR_BRANCH: ${{ github.head_ref }}
          SONAR_PR_BASE: ${{ github.base_ref }}
        run: |
          ./gradlew sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=cardano-foundation \
          -Dsonar.projectKey=cardano-foundation_cf-lob-platform \
          -Dsonar.branch.name=${{ github.head_ref }}