-- Spending event publishing tables (blockchain_publisher module).
-- Mirrors the spending entities in
-- org.cardanofoundation.lob.app.blockchain_publisher.domain.entity.spending.

CREATE TABLE blockchain_publisher_spending_event (
   event_id VARCHAR(36) NOT NULL,
   project_id CHAR(64) NOT NULL,
   funding_id VARCHAR(255) NOT NULL,
   activity_id VARCHAR(255) NOT NULL,
   activity_title VARCHAR(255),
   round_id VARCHAR(255),
   funding_tx VARCHAR(255),
   funding_doc_hash VARCHAR(255),

   event_type VARCHAR(20) NOT NULL,
   event_date DATE,
   total_amount NUMERIC(30, 10) NOT NULL DEFAULT 0,
   currency VARCHAR(10) NOT NULL,
   currency_id VARCHAR(50),
   milestone_id VARCHAR(36),

   organisation_id CHAR(64) NOT NULL,
   organisation_name VARCHAR(255) NOT NULL,
   organisation_tax_id_number VARCHAR(255) NOT NULL,
   organisation_country_code blockchain_publisher_country_code_type NOT NULL,
   organisation_currency_id blockchain_publisher_currency_id_type NOT NULL,

   l1_transaction_hash CHAR(64),
   l1_absolute_slot BIGINT,
   l1_creation_slot BIGINT,
   l1_publish_status blockchain_publisher_blockchain_publish_status_type,
   l1_finality_score blockchain_publisher_finality_score_type,
   l1_publish_status_error_reason TEXT,
   l1_publish_retry SMALLINT,

   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   locked_at TIMESTAMP WITHOUT TIME ZONE,

   PRIMARY KEY (event_id)
);

CREATE TABLE blockchain_publisher_spending_item (
   item_id VARCHAR(36) NOT NULL,
   event_id VARCHAR(36),
   category VARCHAR(255) NOT NULL,
   vendor VARCHAR(255) NOT NULL,
   amount_fcy NUMERIC(30, 10) NOT NULL,
   amount_rcy NUMERIC(30, 10) NOT NULL,
   currency VARCHAR(10) NOT NULL,
   currency_id VARCHAR(50),
   fx_rate NUMERIC(30, 15) NOT NULL,
   spend_date DATE NOT NULL,
   document_hash VARCHAR(255),
   notes TEXT,

   PRIMARY KEY (item_id),
   CONSTRAINT fk_bp_spending_item_event FOREIGN KEY (event_id)
       REFERENCES blockchain_publisher_spending_event (event_id)
);

CREATE TABLE blockchain_publisher_event_milestone_allocation (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   event_id VARCHAR(36),
   milestone_id VARCHAR(36) NOT NULL,
   milestone_label VARCHAR(255) NOT NULL,
   allocated_amount NUMERIC(30, 10) NOT NULL,
   currency VARCHAR(10) NOT NULL,
   currency_id VARCHAR(50),
   due_date DATE NOT NULL,

   PRIMARY KEY (id),
   CONSTRAINT fk_bp_milestone_allocation_event FOREIGN KEY (event_id)
       REFERENCES blockchain_publisher_spending_event (event_id)
);

-- Envers audit tables (entities are @Audited).

CREATE TABLE blockchain_publisher_spending_event_aud (
   event_id VARCHAR(36) NOT NULL,
   project_id CHAR(64),
   funding_id VARCHAR(255),
   activity_id VARCHAR(255),
   activity_title VARCHAR(255),
   round_id VARCHAR(255),
   funding_tx VARCHAR(255),
   funding_doc_hash VARCHAR(255),

   event_type VARCHAR(20),
   event_date DATE,
   total_amount NUMERIC(30, 10),
   currency VARCHAR(10),
   currency_id VARCHAR(50),
   milestone_id VARCHAR(36),

   organisation_id CHAR(64),
   organisation_name VARCHAR(255),
   organisation_tax_id_number VARCHAR(255),
   organisation_country_code blockchain_publisher_country_code_type,
   organisation_currency_id blockchain_publisher_currency_id_type,

   l1_transaction_hash CHAR(64),
   l1_absolute_slot BIGINT,
   l1_creation_slot BIGINT,
   l1_publish_status blockchain_publisher_blockchain_publish_status_type,
   l1_finality_score blockchain_publisher_finality_score_type,
   l1_publish_status_error_reason TEXT,
   l1_publish_retry SMALLINT,

   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   locked_at TIMESTAMP WITHOUT TIME ZONE,

   rev INTEGER NOT NULL,
   revtype SMALLINT NOT NULL,

   CONSTRAINT pk_blockchain_publisher_spending_event_aud PRIMARY KEY (event_id, rev, revtype),
   FOREIGN KEY (rev) REFERENCES revinfo (rev) MATCH SIMPLE
   ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE blockchain_publisher_spending_item_aud (
   item_id VARCHAR(36) NOT NULL,
   event_id VARCHAR(36),
   category VARCHAR(255),
   vendor VARCHAR(255),
   amount_fcy NUMERIC(30, 10),
   amount_rcy NUMERIC(30, 10),
   currency VARCHAR(10),
   currency_id VARCHAR(50),
   fx_rate NUMERIC(30, 15),
   spend_date DATE,
   document_hash VARCHAR(255),
   notes TEXT,

   rev INTEGER NOT NULL,
   revtype SMALLINT NOT NULL,

   CONSTRAINT pk_blockchain_publisher_spending_item_aud PRIMARY KEY (item_id, rev, revtype),
   FOREIGN KEY (rev) REFERENCES revinfo (rev) MATCH SIMPLE
   ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE blockchain_publisher_event_milestone_allocation_aud (
   id BIGINT NOT NULL,
   event_id VARCHAR(36),
   milestone_id VARCHAR(36),
   milestone_label VARCHAR(255),
   allocated_amount NUMERIC(30, 10),
   currency VARCHAR(10),
   currency_id VARCHAR(50),
   due_date DATE,

   rev INTEGER NOT NULL,
   revtype SMALLINT NOT NULL,

   CONSTRAINT pk_blockchain_publisher_event_milestone_allocation_aud PRIMARY KEY (id, rev, revtype),
   FOREIGN KEY (rev) REFERENCES revinfo (rev) MATCH SIMPLE
   ON UPDATE NO ACTION ON DELETE NO ACTION
);
